### ISSUE TITLE
Unknown custom element: <multiselect> when using vueMultiSelect

### ISSUE THREAD

**Issue by dflock** [icebob/vue-form-generator#100]
This is with these versions:

```
  "dependencies": {
    "vue": "^2.1.6",
    "vue-form-generator": "^2.0.0-beta1",
    "vue-multiselect": "next"
  },
```

When I try to use a `vueMultiSelect` field, I get this error in the console:

```
[Vue warn]: Unknown custom element: <multiselect> - did you register the component correctly? For recursive components, make sure to provide the "name" option. 
(found in component <field-vueMultiSelect>)
```

Here's all the relevant code:

### main.js
```
import Vue from 'vue'
import VueFormGenerator from 'vue-form-generator'
Vue.use(VueFormGenerator)

window.VueFormGenerator = VueFormGenerator

import MyComponent from './components/MyComponent.vue'
```

### MyComponent.vue
```
<template lang='html'>
  <div id='my-component'>
    <form>
      <vue-form-generator :schema='schema' :model='model' :options='formOptions'></vue-form-generator>
    </form>
  </div>
</template>

<script>
import Multiselect from 'vue-multiselect'
window.VueMultiselect = Multiselect

export default {
  name: 'my-component',
  components: { Multiselect },
  data () {
    return {
      model: {
        skills: ['Javascript', 'VueJS'],
      },
      schema: {
        fields: [
          {
            type: 'vueMultiSelect',
            multiSelect: true,
            label: 'Skills',
            model: 'skills',
            values: ['Javascript', 'VueJS', 'CSS3', 'HTML5']
          }
        ]
      }
    }
  }
}
</script>
```

I was initially getting this error as well:
```
'vue-multiselect' is missing. Please download from https://github.com/monterail/vue-multiselect and load the script in the HTML head section!
```

which comes from [here](https://github.com/icebob/vue-form-generator/blob/next/src/fields/fieldVueMultiSelect.vue#L103).

I added the import and `window.` at the top of MyComponent to fix this, by trying to do what fieldVueMultiSelect.vue is expecting. That got rid of that error, but I still get the `Unknown custom element: <multiselect>` error.

**Comment by icebob** [comment]
In v2 beta I didn't tested all external libs/fields yet.

**Comment by WalterWeidner** [comment]
I'm also getting this in new project: 
`import Vue from 'vue';
import Multiselect from 'vue-multiselect';

import template from './index.html';
import search from './search/index';

Vue.component(Multiselect);

console.log(Multiselect);

new Vue({
  components: {
    search: search
  },
  el: '.js-page',
  template: template
});
`

**Comment by icebob** [comment]
I fixed this error in [v2.0.0-beta2](https://github.com/icebob/vue-form-generator/releases/tag/v2.0.0-beta2)

**Comment by icebob** [comment]
Dev app for multiselect test: https://github.com/icebob/vue-form-generator/tree/next/dev/multiselect

**Comment by RIanDeLaCruz** [comment]
Somehow, I'm still getting errors.

Using Vue 2.3.3, Vue Form Generator 2.0.0, Vue Multiselect 2.0.3

**Comment by chteuchteu** [comment]
This error is still thrown. Is there any way to make it work?

**Comment by stravi** [comment]
Register the component globally.
Add this to your `main.js` before `new Vue()`
```
import Multiselect from 'vue-multiselect';
Vue.component('multiselect', Multiselect);
```

And ofc don't forget to import CSS style for Multiselect. Example [here](https://vue-generators.gitbook.io/vue-generators/fields/optional_fields/vuemultiselect#css)
